$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json

name: hf-hubert-v1
endpoint_name: hf-hubert2-endpoint-sti

model: azureml:<model-name>:<version>
environment: azureml:<env-name>:<version>

instance_type: Standard_DS1_v2
instance_count: 1

request_settings:
  request_timeout_ms: 60000

code_configuration:
  code: .
  scoring_script: score.py
